### ISSUE TITLE
[Feature] Add subject to the guard expressions

### ISSUE THREAD

**Issue by meDavid** [GlobalTradingTechnologies/workflow-extensions-bundle#6]
I find my self writing a lot of event.getSubject() in guard expressions. Wouldn't it be a good option to add this to the expression context in https://github.com/GlobalTradingTechnologies/workflow-extensions-bundle/blob/5266c0c9b35bb3867c383bcfb0e4caedfa804f20/Guard/ExpressionGuard.php#L123

Every GuardEvent has a subject. This would make my expressions a bit more readable.

**Comment by fduch** [comment]
Hi @meDavid!

Sorry for late reply. 

I am not sure that it worth to implement this feature in terms of uniformity of contexts of expressions evaluated in different parts of the bundle. 

For now we have [ExpressionGuard](https://github.com/GlobalTradingTechnologies/workflow-extensions-bundle/blob/5266c0c9b35bb3867c383bcfb0e4caedfa804f20/Guard/ExpressionGuard.php#L123), all the action listeners that [resolve action arguments through expressions](https://github.com/GlobalTradingTechnologies/workflow-extensions-bundle/blob/5266c0c9b35bb3867c383bcfb0e4caedfa804f20/Trigger/Event/AbstractActionListener.php#L111) (not documented yet) and [ExpressionListener](https://github.com/GlobalTradingTechnologies/workflow-extensions-bundle/blob/5266c0c9b35bb3867c383bcfb0e4caedfa804f20/Trigger/Event/ExpressionListener.php#L77) -  all of them have `event` variable in context without trying to expose it parts as separate variables. 
If we decide to introduce subject as variable along with guard event variable would it be consequentially
to introduce other parts of this event (marking, transition) as variables too? I don't think so for now.

**Comment by meDavid** [comment]
@fduch Guard expressions are now available with the Symfony 3.3 workflow component (https://github.com/symfony/symfony/pull/21935). So this might be no longer relevant.
